/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Return health status of the API server.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Progress
         * @description Return daily and weekly application progress metrics.
         */
        get: operations["get_progress_api_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue
         * @description Return ranked daily queue items.
         */
        get: operations["get_queue_api_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/needs-jd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Needs Jd
         * @description Return jobs awaiting full JD paste.
         */
        get: operations["get_needs_jd_api_needs_jd_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Detail
         * @description Return complete job details including analysis, score, and drafts.
         */
        get: operations["get_job_detail_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare Job
         * @description Prepare application draft materials for a job.
         */
        post: operations["prepare_job_api_jobs__job_id__prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Job
         * @description Transition a job's status and record application metadata.
         */
        post: operations["mark_job_api_jobs__job_id__mark_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Job
         * @description Mark a job as skipped.
         */
        post: operations["skip_job_api_jobs__job_id__skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/jd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Jd
         * @description Attach full job description text to a job.
         */
        post: operations["add_jd_api_jobs__job_id__jd_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Applications
         * @description List applications optionally filtered by job status.
         */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/follow-ups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Follow Ups
         * @description List applied jobs where follow-up is due.
         */
        get: operations["get_follow_ups_api_follow_ups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Question
         * @description Generate or retrieve an answer to an application question.
         */
        post: operations["ask_question_api_answers_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Answers
         * @description List all questions and stored answers in the answer bank.
         */
        get: operations["list_answers_api_answers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers/{answer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Answer
         * @description Supply or update an answer for an answer bank item.
         */
        put: operations["update_answer_api_answers__answer_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers/{answer_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Answer
         * @description Mark an answer bank entry as approved.
         */
        post: operations["approve_answer_api_answers__answer_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Return application funnel and conversion statistics.
         */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile Report
         * @description Return validation report and gap analysis for profile.yaml and resume.
         */
        get: operations["get_profile_report_api_profile_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Run
         * @description Trigger the daily pipeline in a background thread.
         */
        post: operations["trigger_run_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Status
         * @description Return status of the active or most recent pipeline run.
         */
        get: operations["get_run_status_api_run_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionSuccessResponse */
        ActionSuccessResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** AddJDRequest */
        AddJDRequest: {
            /** Text */
            text: string;
        };
        /** AddJDResult */
        AddJDResult: {
            /** Job Id */
            job_id: number;
            /** Status */
            status: string;
            /** Char Count */
            char_count: number;
        };
        /** AnswerBankItem */
        AnswerBankItem: {
            /** Id */
            id: number;
            /** Question Norm */
            question_norm: string;
            /** Category */
            category: string;
            /** Answer */
            answer: string;
            /** Approved */
            approved: boolean;
            /** Source Job Id */
            source_job_id?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * AnswerResult
         * @description Outcome of answering one application question.
         */
        AnswerResult: {
            /** Question */
            question: string;
            /** Question Norm */
            question_norm: string;
            /** Category */
            category: string;
            /** Answer */
            answer: string;
            /** Is Draft */
            is_draft: boolean;
            /** Answer Bank Id */
            answer_bank_id?: number | null;
            /**
             * From Bank
             * @default false
             */
            from_bank: boolean;
        };
        /** ApplicationDraft */
        ApplicationDraft: {
            /** Id */
            id?: number | null;
            /** Job Id */
            job_id: number;
            /** Tailored Summary */
            tailored_summary?: string | null;
            /** Short Note */
            short_note?: string | null;
            /** Outreach Draft */
            outreach_draft?: string | null;
            /** Bullet Ids */
            bullet_ids?: string[];
            /** Prepared At */
            prepared_at?: string | null;
            /** Applied At */
            applied_at?: string | null;
            /** Channel */
            channel?: string | null;
            /** Referral Contact */
            referral_contact?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ApplicationItem */
        ApplicationItem: {
            /** Job Id */
            job_id: number;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Url */
            url?: string;
            /** Location */
            location?: string | null;
            /** Posted At */
            posted_at?: string | null;
            /** Has Description */
            has_description?: boolean;
            /** Applied At */
            applied_at?: string | null;
            /** Channel */
            channel?: string | null;
            /** Notes */
            notes?: string | null;
            /** Referral Contact */
            referral_contact?: string | null;
            /** Prepared At */
            prepared_at?: string | null;
            /** Tailored Summary */
            tailored_summary?: string | null;
            /** Short Note */
            short_note?: string | null;
        };
        /** JobListItem */
        JobListItem: {
            /** Job Id */
            job_id: number;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Url */
            url?: string;
            /** Location */
            location?: string | null;
            /** Posted At */
            posted_at?: string | null;
        };
        /**
         * ApplicationStats
         * @description Weekly application performance over the evaluation window.
         */
        ApplicationStats: {
            /** Weeks */
            weeks: components["schemas"]["WeeklyAppStats"][];
            /** Total Applied */
            total_applied: number;
            /** Weekly Target */
            weekly_target: number;
            /** Avg Per Week */
            avg_per_week: number;
        };
        /** AskQuestionRequest */
        AskQuestionRequest: {
            /** Question */
            question: string;
            /** Job Id */
            job_id?: number | null;
        };
        /**
         * ConversionStats
         * @description Response and interview metrics for a category (source or tier).
         */
        ConversionStats: {
            /** Name */
            name: string;
            /** Applied */
            applied: number;
            /** Responses */
            responses: number;
            /** Interviews */
            interviews: number;
            /** Offers */
            offers: number;
            /** Response Rate */
            response_rate: number;
            /**
             * Rejected
             * @default 0
             */
            rejected: number;
        };
        /** FollowUpItem */
        FollowUpItem: {
            /** Job Id */
            job_id: number;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Applied At */
            applied_at: string;
            /** Days Since Applied */
            days_since_applied: number;
            /** Channel */
            channel?: string | null;
            /** Referral Contact */
            referral_contact?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * FullStatsReport
         * @description Combined report returned by get_stats_report.
         */
        FullStatsReport: {
            funnel: components["schemas"]["FunnelStats"];
            applications: components["schemas"]["ApplicationStats"];
            /** Sources */
            sources: components["schemas"]["ConversionStats"][];
            /** Tiers */
            tiers: components["schemas"]["ConversionStats"][];
        };
        /**
         * FunnelStats
         * @description Funnel counts across the full job lifecycle.
         */
        FunnelStats: {
            /** Total Discovered */
            total_discovered: number;
            /** Filtered */
            filtered: number;
            /** Needs Jd */
            needs_jd: number;
            /** Analyzed */
            analyzed: number;
            /** Scored */
            scored: number;
            /** Queued */
            queued: number;
            /** Prepared */
            prepared: number;
            /** Applied */
            applied: number;
            /** Replied */
            replied: number;
            /** Interview */
            interview: number;
            /** Offer */
            offer: number;
            /** Rejected */
            rejected: number;
            /** Skipped */
            skipped: number;
            /** Expired */
            expired: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /**
             * Total Applied All Time
             * @default 0
             */
            total_applied_all_time: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * JobAnalysis
         * @description Structured data extracted from a job description by the LLM.
         */
        JobAnalysis: {
            /** Normalized Title */
            normalized_title: string;
            /**
             * Seniority
             * @default unknown
             */
            seniority: string;
            /** Experience Min Years */
            experience_min_years?: number | null;
            /** Experience Max Years */
            experience_max_years?: number | null;
            /** Required Skills */
            required_skills?: string[];
            /** Preferred Skills */
            preferred_skills?: string[];
            /**
             * Responsibilities Summary
             * @default
             */
            responsibilities_summary: string;
            /**
             * Location Type
             * @default unknown
             */
            location_type: string;
            /** Locations */
            locations?: string[];
            remote_eligibility?: components["schemas"]["RemoteEligibility"];
            /**
             * Visa Or Work Auth Required
             * @default false
             */
            visa_or_work_auth_required: boolean;
            salary?: components["schemas"]["Salary"];
            /** Red Flags */
            red_flags?: string[];
        };
        /** JobDetail */
        JobDetail: {
            /** Id */
            id: number;
            /** Fingerprint */
            fingerprint: string;
            /** Source */
            source: string;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Location */
            location?: string | null;
            /** Remote Type */
            remote_type?: string | null;
            /** Url */
            url: string;
            /** Apply Url */
            apply_url?: string | null;
            /** Description */
            description?: string | null;
            /** Snippet */
            snippet?: string | null;
            /** Posted At */
            posted_at?: string | null;
            /** Discovered At */
            discovered_at: string;
            /** Last Seen At */
            last_seen_at: string;
            /** Status */
            status: string;
            /** Status Reason */
            status_reason?: string | null;
            analysis?: components["schemas"]["JobAnalysis"] | null;
            score?: components["schemas"]["ScoreDetail"] | null;
            application?: components["schemas"]["ApplicationDraft"] | null;
        };
        /** JobStatusUpdate */
        JobStatusUpdate: {
            /** Job Id */
            job_id: number;
            /** Previous Status */
            previous_status: string;
            /** New Status */
            new_status: string;
            /** Channel */
            channel?: string | null;
            /** Note */
            note?: string | null;
            /** Referral Contact */
            referral_contact?: string | null;
            /** Timestamp */
            timestamp: string;
        };
        /** MarkJobRequest */
        MarkJobRequest: {
            /** Status */
            status: string;
            /** Channel */
            channel?: string | null;
            /** Note */
            note?: string | null;
            /** Referral Contact */
            referral_contact?: string | null;
        };
        /**
         * NeedsJdItem
         * @description Job requiring full description input.
         */
        NeedsJdItem: {
            /** Job Id */
            job_id: number;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Location */
            location: string;
            /** Url */
            url: string;
        };
        /**
         * PrepareResult
         * @description Outcome of preparing one job.
         */
        PrepareResult: {
            /** Job Id */
            job_id: number;
            /** Tier */
            tier: string;
            /** Summary */
            summary: string;
            /** Note */
            note: string;
            /** Bullet Ids */
            bullet_ids?: string[];
            /** Outreach Draft */
            outreach_draft?: string | null;
            /**
             * Used Fallback
             * @default false
             */
            used_fallback: boolean;
            /** Validation Errors */
            validation_errors?: string[] | null;
        };
        /** ProfileReport */
        ProfileReport: {
            /** Validation Errors */
            validation_errors?: string[];
            /** Validation Warnings */
            validation_warnings?: string[];
            /** Unset Settings */
            unset_settings?: string[];
            /** Unmatched Skills */
            unmatched_skills?: [
                string,
                number
            ][];
        };
        /** ProgressSummary */
        ProgressSummary: {
            /** Applied Today */
            applied_today: number;
            /** Daily Size */
            daily_size: number;
            /** Applied This Week */
            applied_this_week: number;
            /** Weekly Target */
            weekly_target: number;
            /** Follow Ups Due Count */
            follow_ups_due_count: number;
        };
        /**
         * QueueItem
         * @description Single item in the daily ranked queue.
         */
        QueueItem: {
            /** Rank */
            rank: number;
            /** Job Id */
            job_id: number;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Location */
            location: string;
            /** Tier */
            tier: string;
            /** Score */
            score: number;
            /** Matched Skills */
            matched_skills: string;
            /** Gaps */
            gaps: string;
            /** Flags */
            flags: string;
            /** Url */
            url: string;
            /** Prepared */
            prepared: string;
        };
        /** RemoteEligibility */
        RemoteEligibility: {
            /**
             * Open To India
             * @default unclear
             */
            open_to_india: string;
            /** Restriction Text */
            restriction_text?: string | null;
        };
        /** RunStageItem */
        RunStageItem: {
            /** Name */
            name: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Counts */
            counts?: unknown;
            /** Error */
            error?: string | null;
        };
        /** RunStatusResponse */
        RunStatusResponse: {
            /**
             * State
             * @default idle
             */
            state: string;
            /** Stages */
            stages?: components["schemas"]["RunStageItem"][];
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            summary?: components["schemas"]["RunSummary"] | null;
            /** Error */
            error?: string | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Stages */
            stages?: components["schemas"]["StageSummary"][];
            /**
             * New Jobs
             * @default 0
             */
            new_jobs: number;
            /**
             * Queued Count
             * @default 0
             */
            queued_count: number;
            /**
             * Tier A Count
             * @default 0
             */
            tier_a_count: number;
            /**
             * Needs Jd Count
             * @default 0
             */
            needs_jd_count: number;
            /**
             * Prepared Count
             * @default 0
             */
            prepared_count: number;
            /**
             * Follow Ups Due Count
             * @default 0
             */
            follow_ups_due_count: number;
            /**
             * Has Failures
             * @default false
             */
            has_failures: boolean;
        };
        /** Salary */
        Salary: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Currency */
            currency?: string | null;
            /** Period */
            period?: string | null;
        };
        /** ScoreDetail */
        ScoreDetail: {
            /** Total */
            total: number;
            /** Tier */
            tier: string;
            /** Skills Score */
            skills_score?: number | null;
            /** Experience Score */
            experience_score?: number | null;
            /** Seniority Score */
            seniority_score?: number | null;
            /** Location Score */
            location_score?: number | null;
            /** Extras Score */
            extras_score?: number | null;
            /** Covered Skills */
            covered_skills?: components["schemas"]["SkillEvidenceItem"][];
            /** Partial Skills */
            partial_skills?: components["schemas"]["SkillEvidenceItem"][];
            /** Learning Only Skills */
            learning_only_skills?: components["schemas"]["SkillEvidenceItem"][];
            /** Missing Skills */
            missing_skills?: string[];
            /** Flags */
            flags?: string[];
            /** Scored At */
            scored_at: string;
        };
        /** SetAnswerRequest */
        SetAnswerRequest: {
            /** Answer Text */
            answer_text: string;
        };
        /** SkillEvidenceItem */
        SkillEvidenceItem: {
            /** Skill */
            skill: string;
            /** Level */
            level: string;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** StageSummary */
        StageSummary: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /** Summary */
            summary?: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WeeklyAppStats
         * @description Application volume for a single calendar week.
         */
        WeeklyAppStats: {
            /** Iso Week */
            iso_week: string;
            /** Week Start */
            week_start: string;
            /** Week End */
            week_end: string;
            /** Count */
            count: number;
            /** Target */
            target: number;
            /** Pct Of Target */
            pct_of_target: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_progress_api_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSummary"];
                };
            };
        };
    };
    get_queue_api_queue_get: {
        parameters: {
            query?: {
                size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_needs_jd_api_needs_jd_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedsJdItem"][];
                };
            };
        };
    };
    get_job_detail_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_job_api_jobs__job_id__prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrepareResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_job_api_jobs__job_id__mark_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_job_api_jobs__job_id__skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_jd_api_jobs__job_id__jd_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddJDRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddJDResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_applications_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_follow_ups_api_follow_ups_get: {
        parameters: {
            query?: {
                days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUpItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question_api_answers_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_answers_api_answers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerBankItem"][];
                };
            };
        };
    };
    update_answer_api_answers__answer_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionSuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_answer_api_answers__answer_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionSuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: {
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FullStatsReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_report_api_profile_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileReport"];
                };
            };
        };
    };
    trigger_run_api_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
        };
    };
    get_run_status_api_run_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
        };
    };
}
