/**
 * Re-export types generated by openapi-typescript.
 * Never hand-write types for API payloads.
 */

import type { components } from './schema';

export type Schema = components['schemas'];
export type ProgressSummary = Schema['ProgressSummary'];
export type QueueItem = Schema['QueueItem'];
export type NeedsJdItem = Schema['NeedsJdItem'];
export type JobDetail = Schema['JobDetail'];
export type ScoreDetail = Schema['ScoreDetail'];
export type SkillEvidenceItem = Schema['SkillEvidenceItem'];
export type ApplicationDraft = Schema['ApplicationDraft'];
export type FollowUpItem = Schema['FollowUpItem'];
export type ApplicationItem = Schema['ApplicationItem'];
export type JobListItem = Schema['JobListItem'];
export type AnswerBankItem = Schema['AnswerBankItem'];
export type FullStatsReport = Schema['FullStatsReport'];
export type ProfileReport = Schema['ProfileReport'];
export type RunStatusResponse = Schema['RunStatusResponse'];
export type RunStageItem = Schema['RunStageItem'];
export type RunSummary = Schema['RunSummary'];
export type PrepareResult = Schema['PrepareResult'];
export type JobStatusUpdate = Schema['JobStatusUpdate'];
export type MarkJobRequest = Schema['MarkJobRequest'];
export type AddJDResult = Schema['AddJDResult'];
export type AnswerResult = Schema['AnswerResult'];
export type SetAnswerRequest = Schema['SetAnswerRequest'];
export type AskQuestionRequest = Schema['AskQuestionRequest'];
export type ActionSuccessResponse = Schema['ActionSuccessResponse'];
export type ConversionStats = Schema['ConversionStats'];
export type FunnelStats = Schema['FunnelStats'];
export type WeeklyAppStats = Schema['WeeklyAppStats'];
export type ApplicationStats = Schema['ApplicationStats'];

